name: payment_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockito:
  bloc_test:
  equatable: 2.0.5
  flutter_bloc: ^7.3.3
  fpdart: ^0.2.0
  dio: ^5.4.0
  animate_do:
  get_it: ^7.2.0
  toastification:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus:
#  auto_route: ^5.0.2  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.1.1
  hive_generator:
 # auto_route_generator: 5.0.3


flutter:
  uses-material-design: true
